### ISSUE TITLE
RSS URLs malformed

### ISSUE THREAD

**Issue by meedstrom** [ASKurz/my_blog#3]
Hi, I'd love to follow your blog, but the feed isn't giving me posts in Elfeed.

Firefox with Feed Indicator shows this when visiting https://solomonkurz.netlify.app/post/index.xml:

![Screenshot showing "Malformed URL: /post/2021-06-..."](https://user-images.githubusercontent.com/68893079/109502840-6e0b1a00-7a91-11eb-984f-f4f112c05c90.png)
Screenshot showing "Malformed URL: /post/2021-06-26-..."

By the way, if you're going to look over your feed anyway, Elfeed writer Chris Wellons points out that Atom is much easier than RSS to write readers for: https://nullprogram.com/blog/2013/09/23/  Since you seem to enjoy nice software, it's a suggestion :-)

**Comment by meedstrom** [comment]
That's odd, it actually works now. My bad. Although relative URLs are still considered malformed in RSS: https://www.rssboard.org/rss-profile#data-types-url

**Comment by meedstrom** [comment]
So the feed items show up in my reader, but they're truncated and the link points to a relative URL, which leads nowhere, which is pretty impractical:

![Screenshot from 2021-03-01 14-49-00](https://user-images.githubusercontent.com/68893079/109505873-f0e1a400-7a94-11eb-81a2-57ed6abe6201.png)

**Comment by ASKurz** [comment]
Hey @meedstrom, thanks for opening this issue. At the moment, I don't know any thing about Elfeed, Atom, or RSS--like I'm a complete deer-in-the-headlights novice on this one. So I'll schedule in some time to do some reading, but I don't imagine this is going to get fixed anytime soon.

**Comment by meedstrom** [comment]
Hi @ASKurz and thanks for the reply. Loved Statistical Rethinking with brms, by the way :-)

The primary thing I would request is to not truncate the feed items, so we can read the whole post in our feed reader - and then the relative URLs are irrelevant. 

Elfeed is just one of many feed-reader programs/apps. Admittedly one of the odder-looking ones.

**Comment by ASKurz** [comment]
Following changes to the underlying **blogdown** software, I just overhauled the website. As part of the update, the most recent blog post is at https://solomonkurz.netlify.app/post/2021-04-22-effect-sizes-for-experimental-trials-analyzed-with-multilevel-growth-models-two-of-two/. Let me know if this worked for Elfeed.

**Comment by meedstrom** [comment]
It works, both the link and the nontruncation. Thank you! Keep on being awesome.

**Comment by ASKurz** [comment]
Good deal.
